### ISSUE TITLE
Monthly Maintenance 04/2023

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/ci#49]
**T2: update Terraform providers**
[INFO](https://github.com/stackabletech/infrastructure/blob/main/maintenance/maintenance.adoc#t2-update-terraform-providers)

- [x] research for new versions
- [x] Hetzner
- [x] AWS (https://github.com/stackabletech/t2/issues/427, postponed since 03/2023)
- [x] IONOS
- [x] Azure
- [x] GKE
- [x] test the templates in Jenkins
- [x] Investigate problem with HCloud K3s Debian 10

**Check for new Nexus version**
[INFO](https://github.com/stackabletech/infrastructure/blob/main/maintenance/maintenance.adoc#check-for-new-nexus-version)

- [x] check if a new Nexus version is available
- [x] create GitHub issue using the template (https://github.com/stackabletech/infrastructure/issues/104)
- [x] complete GitHub issue

**Check for new Jenkins version**
[INFO](https://github.com/stackabletech/infrastructure/blob/main/maintenance/maintenance.adoc#check-for-new-jenkins-version)

- [x] check if a new Jenkins version is available
- [x] create GitHub issue using the template (https://github.com/stackabletech/infrastructure/issues/107)
- [x] complete GitHub issue

**Check free space on logging servers**

- [x] check free space on https://logs.t2.stackable.tech
- [x] check free space on https://logs.t2-dev.stackable.tech

**Comment by backstreetkiwi** [comment]
After Terraform update: one error here: https://ci.stackable.tech/view/06%20T2/job/T2-all-platform-test/PLATFORM_ID=ionos-k3s-debian-11/

**Comment by backstreetkiwi** [comment]
Another problem after Terraform update (most probably not related): This one timed out during K3s Agent installation: https://ci.stackable.tech/job/T2-all-platform-test/PLATFORM_ID=hcloud-k3s-debian-10/12/console
