### ISSUE TITLE
Add support for test suites

### ISSUE THREAD

**Issue by razvan** [stackabletech/ci#62]
# Description

Jenkins should use the new `--suite` beku option to run test suites.

# Acceptance

* nightly test run the `nightly` test suite which may be different per product/operator.
* The UI for custom tests has a new field that allows the user to enter a suite name. If nothing is entered, Jenkins runs the `default` test suite.
* There is an alternative script to `scripts/run_tests.sh` that can pass the --suite to `beku`. 

# Nightly suite added to operator:

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/296
- [x] commons-operator - has no tests
- [ ] https://github.com/stackabletech/druid-operator/pull/449
- [ ] https://github.com/stackabletech/edc-operator/pull/17
- [ ] https://github.com/stackabletech/hbase-operator/pull/372
- [ ] https://github.com/stackabletech/hdfs-operator/pull/369
- [ ] https://github.com/stackabletech/hive-operator/pull/351
- [ ] https://github.com/stackabletech/kafka-operator/pull/601
- [ ] https://github.com/stackabletech/listener-operator/pull/86
- [ ] https://github.com/stackabletech/nifi-operator/pull/482
- [ ] https://github.com/stackabletech/opa-operator/pull/457
- [ ] https://github.com/stackabletech/secret-operator/pull/291
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/255
- [ ] https://github.com/stackabletech/superset-operator/pull/378
- [ ] https://github.com/stackabletech/trino-operator/pull/439
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/701
```

Notes: this should help  reduce test [flakiness](https://github.com/stackabletech/issues/issues/364)

**Comment by lfrancke** [comment]
Can this ticket be closed?

**Comment by razvan** [comment]
yes
